namespace vmsOpenAcars.Models
{
    /// <summary>
    /// Represents a flight plan generated by SimBrief and used throughout the application.
    /// Contains all relevant information about a planned flight including routing,
    /// aircraft details, fuel calculations, and timing information.
    /// </summary>
    /// <remarks>
    /// This model is populated from the SimBrief API JSON response and is used for:
    /// - Displaying flight information in the UI
    /// - Validating departure airport against pilot location
    /// - Prefiling PIREP data to phpVMS
    /// - Calculating fuel usage and flight time during the flight
    /// </remarks>
    public class SimbriefPlan
    {
        #region Flight Information

        /// <summary>
        /// Gets or sets the flight number without airline code.
        /// Example: "55CH", "1234"
        /// </summary>
        public string FlightNumber { get; set; }

        /// <summary>
        /// Gets or sets the ICAO airline code.
        /// Example: "VHR", "DLH", "AAL"
        /// </summary>
        public string Airline { get; set; }

        /// <summary>
        /// Gets or sets the ICAO code of the departure airport.
        /// Example: "SKMD", "KJFK", "EGLL"
        /// </summary>
        public string Origin { get; set; }

        /// <summary>
        /// Gets or sets the ICAO code of the destination airport.
        /// Example: "SKRG", "KLAX", "LFPG"
        /// </summary>
        public string Destination { get; set; }

        /// <summary>
        /// Gets or sets the elevation of the destination airport in feet.
        /// Used for AGL calculations during approach.
        /// </summary>
        public int DestinationElevation { get; set; }

        /// <summary>
        /// Gets or sets the elevation of the origin airport in feet.
        /// Used for AGL calculations during departure.
        /// </summary>
        public int OriginElevation { get; set; }

        /// <summary>
        /// Gets or sets the ICAO code of the alternate airport.
        /// Example: "SKBO", "KORD"
        /// </summary>
        public string Alternate { get; set; }

        /// <summary>
        /// Gets or sets the full route string as provided by SimBrief.
        /// Example: "DCT ISTAX DCT MRN DCT RNG RNG4C"
        /// </summary>
        public string Route { get; set; }
        /// <summary>
        /// Gets or sets the Timestamp Unix (seconds) as provided by SimBrief.
        /// </summary>
        public long TimeGenerated { get; set; }
        /// <summary>
        /// Gets or sets the Schedule Time as provided by SimBrief.
        /// </summary>
        public long ScheduledOffTime { get; set; }

        #endregion

        #region Aircraft Information
        /// <summary>
        /// Gets or sets the phpvms aircraft id
        /// Example: 1,2,53
        /// </summary>
        public int AircraftId { get; set; }
        /// <summary>
        /// Gets or sets the aircraft type code (may be same as AircraftIcao or different).
        /// Example: "B58", "B738"
        /// </summary>
        public string Aircraft { get; set; }

        /// <summary>
        /// Gets or sets the aircraft registration/tail number.
        /// Example: "KH1710", "N665VH"
        /// </summary>
        public string Registration { get; set; }

        /// <summary>
        /// Gets or sets the ICAO aircraft type designator.
        /// Example: "BE58", "B738", "A320"
        /// </summary>
        public string AircraftIcao { get; set; }
        public string FlightId { get; set; }   // phpVMS flight ID 
        public string BidId { get; set; }       // Bid ID

        #endregion

        #region Weight & Fuel

        /// <summary>
        /// Gets or sets the planned block fuel (fuel on board at departure ramp) in the specified units.
        /// </summary>
        public double BlockFuel { get; set; }

        /// <summary>
        /// Gets or sets the actual block fuel from the simulator
        /// </summary>
        public double ActualBlockFuel { get; set; }

        /// <summary>
        /// Gets or sets the original planned block fuel (for reference)
        /// </summary>
        public double PlannedBlockFuel { get; set; }

        /// <summary>
        /// Gets or sets the payload weight in the specified units.
        /// </summary>
        public double PayLoad { get; set; }

        /// <summary>
        /// Gets or sets the Zero Fuel Weight (ZFW) from SimBrief.
        /// This is the weight of the aircraft without fuel.
        /// </summary>
        public double ZeroFuelWeight { get; set; }

        /// <summary>
        /// Gets or sets the number of passengers on board.
        /// </summary>
        public int PaxCount { get; set; }

        /// <summary>
        /// Gets or sets the fuel on board at departure (may be same as BlockFuel).
        /// </summary>
        public double DepartureFuel { get; set; }

        /// <summary>
        /// Gets or sets the units used for fuel and weight measurements.
        /// Example: "kg", "lbs"
        /// </summary>
        public string Units { get; set; }

        #endregion

        #region Timing & Altitude

        /// <summary>
        /// Gets or sets the estimated time enroute in seconds.
        /// This is the planned flight time from takeoff to landing.
        /// </summary>
        public int EstTimeEnroute { get; set; }

        /// <summary>
        /// Gets or sets the planned cruise altitude as a string.
        /// Example: "FL230", "10500", "35000"
        /// </summary>
        public string PlannedAltitude { get; set; }

        /// <summary>
        /// Gets or sets the planned cruise altitude in feet (numeric).
        /// Example: 23000, 10500, 35000
        /// </summary>
        public int CruiseAltitude { get; set; }

        #endregion

        #region Distance

        /// <summary>
        /// Gets or sets the planned route distance in nautical miles (NM).
        /// Sourced from SimBrief <c>route_distance</c> field or phpVMS flight distance.
        /// </summary>
        public double Distance { get; set; }

        #endregion

        #region Files

        /// <summary>
        /// URL directa al PDF del OFP generado por SimBrief.
        /// Construida como files.directory + files.pdf del JSON de SimBrief.
        /// </summary>
        public string PdfUrl { get; set; }

        /// <summary>
        /// Ruta local al PDF del OFP ya descargado. Null si aún no se ha descargado.
        /// Se invalida automáticamente cuando OFPViewerForm elimina el archivo al cerrarse.
        /// </summary>
        public string LocalPdfPath { get; set; }

        #endregion
    }
}